[project]
name = "comfyui-saturnnodes"
description = "Essential workflow controls, mid-generation pausing, real-time queue persistence, folder watcher, and visual model loaders for ComfyUI."
version = "2.4.0"
readme = "README.md"
license = "MIT"
dependencies = ["pillow", "numpy", "piexif"]

[project.optional-dependencies]
tray = ["pystray"]

[project.urls]
Repository = "https://github.com/KOFiblto/ComfyUI-SaturnNodes"

[tool.comfy]
PublisherId = "KOFiblto"
DisplayName = "ComfyUI-SaturnNodes"
Icon = "https://raw.githubusercontent.com/KOFiblto/ComfyUI-SaturnNodes/main/web/logo.png"
